#
# Spring Boot - Common application properties
#  - https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save

  thymeleaf:
    mode: LEGACYHTML5

flyway:
  locations: classpath:db
  check-location: true

---

spring:
  profiles: dev

  redis:
    host: 127.0.0.1
    port: 6379

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    pool-size: 30
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: prod
